ManejoPresupuesto/Controllers/TiposCuentasController.cs
using Dapper;
using ManejoPresupuesto.Models;
using ManejoPresupuesto.Servicios;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.Data.SqlClient;

namespace ManejoPresupuesto.Controllers
{
    /// <summary>
    /// Controlador para manejar las operaciones de los tipos de cuentas.
    /// </summary>
    public class TiposCuentasController : Controller
    {

        #region variables
        private readonly IRepositorioTiposCuentas _resitorioTiposCuentas;
        private readonly IServicioUsuarios _serviciosUsuarios;
        #endregion variables

        #region constructor
        /// <summary>
        /// Inicializa una nueva instancia de <see cref="TiposCuentasController"/> con los servicios necesarios.
        /// </summary>
        /// <param name="repositorioTiposCuentas">El repositorio para operaciones de tipos de cuentas.</param>
        /// <param name="servicioUsuarios">El servicio para operaciones de usuarios.</param>
        public TiposCuentasController(IRepositorioTiposCuentas repositorioTiposCuentas, IServicioUsuarios servicioUsuarios)
        {
            _resitorioTiposCuentas = repositorioTiposCuentas;
            _serviciosUsuarios = servicioUsuarios;
        }

        #endregion constructor
        public IActionResult Crear()
        {
            return View();
        }

        #region POST
        /// <summary>
        /// Procesa la solicitud de creación de un nuevo tipo de cuenta.
        /// </summary>
        /// <param name="tipoCuenta">La instancia de <see cref="TipoCuenta"/> que contiene los datos ingresados por el usuario.</param>
        /// <returns>
        /// Una vista de creación si el modelo no es válido o si la creación falla debido a un nombre de cuenta duplicado o un error inesperado.
        /// Redirige a la acción "ListarPorUsuarioId" si el tipo de cuenta se crea con éxito.
        /// </returns>
        /// <remarks>
        /// Este método realiza varias operaciones importantes:
        /// 1. Verifica si el modelo es válido. Si no lo es, retorna a la vista de creación con los datos ingresados para corrección por parte del usuario.
        /// 2. Asigna el ID del usuario actual al tipo de cuenta, basándose en la sesión o contexto del usuario.
        /// 3. Verifica si ya existe un tipo de cuenta con el mismo nombre para el usuario actual. Si existe, agrega un error al modelo y retorna a la vista de creación.
        /// 4. Intenta crear el nuevo tipo de cuenta en la base de datos. Si la operación es exitosa, redirige al usuario a la lista de sus tipos de cuenta.
        /// 5. Captura cualquier excepción no controlada durante el proceso de creación y agrega un mensaje de error genérico al modelo, retornando a la vista de creación para informar al usuario.
        /// </remarks>
        [HttpPost]
        public async Task<IActionResult> Crear(TipoCuenta tipoCuenta)
        {
            if (!ModelState.IsValid)
            {
                return View(tipoCuenta);
            }

            tipoCuenta.UsuarioId = _serviciosUsuarios.ObtenerUsuarioId();

            try
            {
                bool yaExisteTipoCuenta = await _resitorioTiposCuentas.Existe(tipoCuenta.Nombre, tipoCuenta.UsuarioId);

                if (yaExisteTipoCuenta)
                {
                    ModelState.AddModelError(nameof(tipoCuenta.Nombre), $"El nombre {tipoCuenta.Nombre} ya existe.");
                    return View(tipoCuenta);
                }

                await _resitorioTiposCuentas.Crear(tipoCuenta);
                return RedirectToAction("ListarPorUsuarioId");
            }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, "Ocurrió un error al crear el tipo de cuenta.");
                return View(tipoCuenta);
            }
        }

        /// <summary>
        /// Procesa la solicitud de edición de un tipo de cuenta existente.
        /// </summary>
        /// <param name="tipoCuenta">La instancia de <see cref="TipoCuenta"/> que contiene los datos actualizados ingresados por el usuario.</param>
        /// <returns>
        /// Redirige a la acción "ListarPorUsuarioId" si la actualización es exitosa.
        /// Redirige a la acción "NoEncontrado" del controlador "Home" si el tipo de cuenta a editar no existe o no pertenece al usuario actual.
        /// </returns>
        /// <remarks>
        /// Este método realiza las siguientes operaciones:
        /// 1. Obtiene el ID del usuario actual para asegurar que solo se puedan editar los tipos de cuenta que pertenecen al usuario autenticado.
        /// 2. Verifica que el tipo de cuenta a editar exista en la base de datos y que pertenezca al usuario actual.
        /// 3. Si el tipo de cuenta existe y pertenece al usuario, se procede con la actualización de los datos en la base de datos.
        /// 4. Si la actualización es exitosa, redirige al usuario a la lista de sus tipos de cuenta.
        /// 5. Si el tipo de cuenta no se encuentra o no pertenece al usuario, redirige al usuario a una página de error o página no encontrada.
        /// </remarks>
        [HttpPost]
        public async Task<IActionResult> EditarTipoCuenta(TipoCuenta tipoCuenta)
        {
            var usuarioId = _serviciosUsuarios.ObtenerUsuarioId();

            var tipoCuentaExiste = await _resitorioTiposCuentas.ObtenerPorId(tipoCuenta.Id, usuarioId);

            if (tipoCuentaExiste == null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await _resitorioTiposCuentas.Actualizar(tipoCuenta);
            return RedirectToAction("ListarPorUsuarioId");
        }

        /// <summary>
        /// Procesa la solicitud de eliminación de un tipo de cuenta existente.
        /// </summary>
        /// <param name="tipoCuenta">La instancia de <see cref="TipoCuenta"/> que incluye el ID del tipo de cuenta a eliminar.</param>
        /// <returns>
        /// Redirige a la acción "ListarPorUsuarioId" si la eliminación es exitosa.
        /// Retorna una vista "NotFound" si el ID de usuario no se encuentra.
        /// Redirige a la acción "NoEncontrado" del controlador "Home" si el tipo de cuenta a eliminar no existe o no pertenece al usuario actual.
        /// </returns>
        /// <remarks>
        /// Este método realiza las siguientes operaciones:
        /// 1. Obtiene el ID del usuario actual para asegurar que solo se puedan eliminar los tipos de cuenta que pertenecen al usuario autenticado.
        /// 2. Verifica que el tipo de cuenta a eliminar exista en la base de datos y que pertenezca al usuario actual.
        /// 3. Si el tipo de cuenta existe y pertenece al usuario, procede con la eliminación del tipo de cuenta de la base de datos.
        /// 4. Si la eliminación es exitosa, redirige al usuario a la lista de sus tipos de cuenta.
        /// 5. Si el tipo de cuenta no se encuentra o no pertenece al usuario, redirige al usuario a una página de error o página no encontrada.
        /// </remarks>
        [HttpPost]
        public async Task<IActionResult> EliminarPorId(TipoCuenta tipoCuenta)
        {
            var usuarioId = _serviciosUsuarios.ObtenerUsuarioId();
            if (usuarioId == null)
            {
                return NotFound("Usuario no encontrado");
            }

            var tipoCuentaExiste = await _resitorioTiposCuentas.ObtenerPorId(tipoCuenta.Id, usuarioId);
            if (tipoCuentaExiste == null)
            {
                return RedirectToAction("NoEncontrado", "Home");
            }

            await _resitorioTiposCuentas.Eliminar(tipoCuenta.Id);
            return RedirectToAction("ListarPorUsuarioId");
        }

        /// <summary>
        /// Reordena los tipos de cuenta de un usuario basándose en una nueva secuencia de IDs proporcionada.
        /// </summary>
        /// <param name="ids">Una matriz de enteros que representa la nueva secuencia de IDs de los tipos de cuenta, en el orden deseado.</param>
        /// <returns>
        /// Retorna una respuesta HTTP 200 OK si la reordenación se completa con éxito.
        /// </returns>
        /// <remarks>
        /// Este método realiza las siguientes operaciones:
        /// 1. Obtiene el ID del usuario actual para asegurar que solo se puedan reordenar los tipos de cuenta que pertenecen al usuario autenticado.
        /// 2. Llama al método 'OrdenarForma1' del repositorio de tipos de cuentas, pasándole el ID del usuario y la nueva secuencia de IDs para actualizar el orden de los tipos de cuenta en la base de datos.
        /// 3. Retorna una respuesta HTTP 200 OK para indicar que la operación se completó con éxito.
        /// </remarks>
        [HttpPost]
        public async Task<IActionResult> OrdenarTablaForma1([FromBody] int[] ids)
        {
            int usuarioId = _serviciosUsuarios.ObtenerUsuarioId();

            await _resitorioTiposCuentas.OrdenarForma1(usuarioId, ids);

            return Ok();
        }

        /// <summary>
        /// Reordena los tipos de cuenta de un usuario basándose en un arreglo de IDs proporcionado en el cuerpo de la solicitud.
        /// Este método garantiza que solo los tipos de cuenta que pertenecen al usuario actual sean reordenados, rechazando cualquier
        /// intento de modificar tipos de cuenta que no le pertenecen al usuario.
        /// </summary>
        /// <param name="ids">Arreglo de enteros que representa los IDs de los tipos de cuenta en el nuevo orden deseado.</param>
        /// <returns>
        /// Un resultado de acción Ok() si el reordenamiento es exitoso, indicando que los tipos de cuenta han sido actualizados correctamente.
        /// Un resultado de acción Forbid() si se detecta algún ID en la lista proporcionada que no pertenece a los tipos de cuenta del usuario actual,
        /// indicando un intento no autorizado de reordenar tipos de cuenta que no son del usuario.
        /// </returns>

ManejoPresupuesto/Views/TiposCuentas/Crear.cshtml
@model TipoCuenta
@{
    ViewData["Title"] = "Crear Tipo Cuenta";
}


<h1>Crear Tipo de Cuenta</h1>
<h5>El tipo de cuenta se refiere a como podemos agrupar cuentas. Ejemplos: Prestamos, tarjetas, tarjetas de credito, etc.</h5>
<div asp-validation-summary="ModelOnly" class="text-danger"></div>



<form asp-action ="Crear">
    <div class="mb-3">
    <label asp-for="Nombre" class="form-label"></label>
    <input type="text" asp-for="Nombre" class="form-control" />
    <span asp-validation-for="Nombre" class="text-danger"></span>

    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
    <a class="btn btn-secondary" asp-action="ListarPorUsuarioId">Cancelar</a>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}

ManejoPresupuesto/Views/TiposCuentas/Editar.cshtml
@model TipoCuenta
@{
    ViewData["Title"] = "Editar TIPO cUENTA";
}
<h1>Editar tipo Cuenta: @Model.Nombre</h1>


<div asp-validation-summary="ModelOnly" class="text-danger"></div>



<form asp-action="EditarTipoCuenta">
    <input type="hidden" asp-for="Id" />
    <div class="mb-3">
        <label asp-for="Nombre" class="form-label"></label>
        <input type="text" asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>

    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
    <a class="btn btn-secondary" asp-action="ListarPorUsuarioId">Cancelar</a>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ManejoPresupuesto/Views/TiposCuentas/Eliminar.cshtml
@model TipoCuenta
@{
    ViewData["Title"] = "Eliminar Tipo Cuenta";
}

<h3 class="mb-3">¿Esta seguro que desea borrar el tipo cuenta de @Model.Nombre</h3>

<form asp-action="EliminarPorId">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger">Borrar</button>
    <a class="btn btn-secondary" asp-action="ListarPorUsuarioId">Cancelar</a></form>

ManejoPresupuesto/Views/TiposCuentas/Listar.cshtml
@model IEnumerable<TipoCuenta>

<h2>Listar Tipos de Cuentas</h2>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Id)</td>
                <td>@Html.DisplayFor(modelItem => item.Nombre)</td>
                <td>@Html.DisplayFor(modelItem => item.UsuarioId)</td>
                <td>@Html.DisplayFor(modelItem => item.Orden)</td>
                <td>
                    @Html.ActionLink("Editar", "Editar", new { id = item.Id }) |
                    @Html.ActionLink("Detalles", "Detalles", new { id = item.Id }) |
                    @Html.ActionLink("Eliminar", "Eliminar", new { id = item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

ManejoPresupuesto/Views/TiposCuentas/ListarPorUsuarioId.cshtml
@model IEnumerable<TipoCuenta>
@{
    ViewData["Title"] = "Listar por Usuario Id";

}

<h1>Tipos de cuentas</h1>

<a asp-action="Crear" class="btn-btn-primary">Crear Nuevo</a>
<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody id="reordenable">
        @foreach (var tipoCuenta in Model)
        {
            <tr>
                <td>
                    <input type="hidden" value="@tipoCuenta.Id" class="ids"/>
                    <a class="btn btn-primary" asp-action="Editar" asp-route-id="@tipoCuenta.Id">Editar </a>
                    <a class="btn btn-danger" asp-action="Eliminar" asp-route-id="@tipoCuenta.Id">Borrar </a>
                </td>
                <td>
                    @tipoCuenta.Nombre
                </td>
            </tr>
        }
    </tbody>

@section Scripts {
    <script>

            const urlOrdenar = '@Url.Action("OrdenarTablaForma2", "TiposCuentas")';
        $(function () {
            $("#reordenable").sortable({
                //Cuanod termine de mover columna queremos ejecutar la funcion
                stop: async function (event, ui) {
                    await actualizarOrdenes();
                }
            });
            async function actualizarOrdenes() {
                const ids = obtenerIdsDeElementos();
                await enviarIdsAlBackend(ids);
            }

                 function obtenerIdsDeElementos(){
                    //Obtenesmos los ids de los elementos
                    const ids=$(".ids").map(function(){
                        return $(this).val();
                    }).get();

                    return ids;
                }

                async function enviarIdsAlBackend(ids){
                   var data = JSON.stringify( ids);

                   await fetch(urlOrdenar, {
                       method: 'POST',
                       headers: {
                           'Content-Type': 'application/json'
                       },
                       body: data
                    });
                }
        });
    </script>
}
```